server:
  port: ${PORT :9090}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/produto
    username: admin
    password: admin234
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout : 20000
      maximumPoolSize : 5
